export const planDetails = {
  cignaDhmo: {
    planName: "Cigna Dental Care DHMO",
    offeredBy:
      "Cigna Health and Life Insurance Company, Connecticut General Life Insurance Company, or their affiliates.",
    referenceDocument: "595894 g 06/16",
    overview:
      "Comprehensive dental coverage designed to be easy to use at a wallet-friendly price, with no deductible and no annual dollar maximum on covered services.",
    support: {
      cignaPhone: "800.Cigna24 (800.244.6224)",
      cignaWebsitePreEnroll: "https://www.cigna.com",
      cignaWebsitePostEnroll: "https://mycigna.com",
    },
    corePlanRules: [
      "Member must choose a network general dentist to manage overall dental care.",
      "Covered family members may choose their own network general dentists.",
      "In most states, covered services must be provided through a network general dentist except emergency care.",
      "No deductible applies before benefits begin.",
      "No annual dollar maximum applies to covered services.",
      "Out-of-network care is generally not covered except as required by law or in emergencies.",
    ],
    networkAccess: {
      dentalNetwork:
        "Cigna DHMO network; members should choose a network general dentist within 25 miles when possible for adequate access.",
      findDentist:
        "Search myCigna.com dentist directory (updated weekly) or call customer service for a customized directory by email.",
      specialistRules: [
        "General dentist referral is required for some specialty care.",
        "Children under age 7 may see a network pediatric dentist without referral.",
        "No referral is required to see a network orthodontist or endodontist (check plan materials for actual coverage).",
      ],
    },
    coveredServiceCategories: {
      preventive: [
        "Cleanings",
        "Fluoride",
        "Sealants",
        "Bitewing x-rays",
        "Full mouth x-rays",
        "Oral cancer detection procedures",
      ],
      basic: [
        "Tooth-colored resin/composite fillings",
        "Silver amalgam fillings",
      ],
      major: [
        "Crowns",
        "Bridges",
        "Dentures including those over implants",
        "Root canal treatment",
        "Oral surgery",
        "Extractions",
        "Periodontal (gum) disease treatment",
      ],
      additional: [
        "Orthodontic care (on many plans; verify in plan materials)",
        "Teeth whitening with take-home bleaching trays and gel",
        "Athletic mouth guard creation and adjustments",
        "General anesthesia when medically necessary",
        "TMJ diagnosis and treatment including cone beam x-ray and appliance",
      ],
      note:
        "Covered services are governed by the Patient Charge Schedule (PCS), medical necessity, and state-specific rules.",
    },
    notCoveredExamples: [
      "Experimental and cosmetic dentistry",
      "Treatment or surgery associated with poor or hopeless diagnosis",
      "Recementation of crowns, inlays/onlays, posts/cores, and veneers within 180 days of initial placement",
      "Crowns, bridges, and implant-supported prostheses used only for splinting",
      "Replacement of an occlusal guard beyond one per 24 consecutive months when listed as limited on PCS",
      "Work already in progress under prior plan for crowns, bridges, dentures, root canal treatment, or implant-supported prostheses (subject to state exceptions)",
    ],
    enrollmentAndAdministration: {
      enrollmentSteps: [
        "Review plan materials and PCS",
        "Select a network general dentist",
        "Complete enrollment process per employer or enrollment channel instructions",
        "Register on myCigna.com after enrollment",
      ],
      afterEnrollment: [
        "Member receives ID card, PCS, and additional plan materials",
        "Member pays PCS patient charge for covered services at time of service",
        "Dental office can be changed for any reason, typically effective first of next month",
        "Selection changes generally must be made by the 15th for first-of-next-month effective date",
        "Second opinion from another network general dentist can be arranged through customer service",
      ],
      claimsAndWaiting: "No claim forms and no waiting periods for coverage.",
      preExistingConditions:
        "Pre-existing conditions are not excluded when procedures are covered under PCS, but work already in progress exclusions may apply.",
    },
    enhancedPrograms: {
      oralHealthIntegrationProgram: {
        description:
          "Qualifying members may be reimbursed 100% of eligible out-of-pocket costs for certain dental procedures.",
        qualifyingConditions: [
          "Diabetes",
          "Heart disease",
          "Stroke",
          "Maternity",
          "Head and neck cancer radiation",
          "Organ transplants",
          "Chronic kidney disease",
        ],
      },
      includedSupportPrograms: [
        "Dental Information Line support 24/7/365",
        "Identity theft resolution program support 24/7/365 (service program, not insurance)",
      ],
    },
    complianceNotes: [
      "DHMO is a product label that may differ by state (including prepaid, managed care, and open access features).",
      "Cigna DHMO availability is state dependent and not available in all states and territories.",
      "State-specific non-network reimbursement exceptions are documented for Minnesota and Oklahoma.",
      "Covered and excluded services, alternate coverage provisions, and costs are governed by PCS and applicable law.",
      "California and Texas include specific exceptions for treatment already in progress when otherwise covered by PCS.",
      "Identity theft program is not insurance and does not reimburse financial losses.",
    ],
    stateAvailability: {
      available: [
        "AL",
        "AR",
        "AZ",
        "CA",
        "CO",
        "CT",
        "DC",
        "DE",
        "FL",
        "GA",
        "IA",
        "ID",
        "IL",
        "IN",
        "KS",
        "KY",
        "LA",
        "MA",
        "MD",
        "MI",
        "MN",
        "MO",
        "MS",
        "NC",
        "NE",
        "NJ",
        "NV",
        "NY",
        "OH",
        "OK",
        "OR",
        "PA",
        "SC",
        "TN",
        "TX",
        "UT",
        "VA",
        "WI",
      ],
      notAvailable: [
        "AK",
        "HI",
        "ME",
        "MT",
        "NH",
        "ND",
        "RI",
        "SD",
        "VT",
        "WA",
        "WV",
        "WY",
        "NM",
      ],
    },
  },
  cignaDhmoWithGvsVision: {
    planName: "Cigna Dental (DHMO) W/GVS Vision",
    offeredBy:
      "Cigna Health and Life Insurance Company, Connecticut General Life Insurance Company, or their affiliates.",
    support: {
      cignaPhone: "800.Cigna24 (800.244.6224)",
      cignaWebsitePreEnroll: "https://www.cigna.com",
      cignaWebsitePostEnroll: "https://mycigna.com",
      gvsPhone: "800.VISION.1",
      gvsWebsite: "https://generalvision.com",
    },
    corePlanRules: [
      "Member must choose a network general dentist to manage dental care.",
      "Covered family members can choose their own network general dentists.",
      "In most states, services must go through a network general dentist for coverage to apply (except emergencies).",
      "No deductibles and no annual dollar maximum on covered services.",
      "If a member uses an out-of-network dentist, plan payment is generally not available except as required by law or emergencies.",
    ],
    networkAccess: {
      dentalNetwork: "Cigna DHMO network (one of the largest in the U.S.).",
      findDentist:
        "Use myCigna.com dentist directory (updated weekly) or call customer service for a customized directory.",
      specialistRules: [
        "General dentist referral is required for some specialty care.",
        "Children under age 7 can see a network pediatric dentist without referral.",
        "No referral required for network orthodontists and endodontists (check plan documents for coverage details).",
      ],
    },
    coveredServiceCategories: {
      preventive: [
        "Cleanings",
        "Fluoride",
        "Sealants",
        "Bitewing x-rays",
        "Full mouth x-rays",
        "Oral cancer detection procedures",
      ],
      basic: [
        "Tooth-colored resin/composite fillings",
        "Silver amalgam fillings",
      ],
      major: [
        "Crowns",
        "Bridges",
        "Dentures (including over implants)",
        "Root canals",
        "Oral surgery",
        "Extractions",
        "Periodontal disease treatment",
      ],
      additional: [
        "Orthodontic care on many plans (check plan materials)",
        "Take-home teeth whitening trays and gel",
        "Athletic mouth guard and adjustments",
        "General anesthesia when medically necessary",
        "TMJ diagnosis and treatment including cone beam x-ray and appliance",
      ],
      note:
        "Coverage is subject to the Patient Charge Schedule (PCS), plan terms, medical necessity, and applicable state rules.",
    },
    notCoveredExamples: [
      "Experimental and cosmetic dentistry",
      "Treatments or surgery associated with poor or hopeless prognosis",
      "Recementation of crowns, inlays/onlays, posts/cores, and veneers within 180 days of placement",
      "Crowns, bridges, and implant-supported prostheses used only for splinting",
      "Some replacement limitations (example: occlusal guard beyond one per 24 months when listed on PCS)",
      "Work already in progress from prior coverage for specific procedures (subject to state exceptions)",
    ],
    enrollmentAndAdministration: {
      enrollmentSteps: [
        "Review plan materials and PCS",
        "Select a network general dentist",
        "Complete enrollment process based on employer or enrollment channel instructions",
        "Register on myCigna.com after enrollment",
      ],
      afterEnrollment: [
        "Member receives ID card, PCS, and plan materials",
        "Member pays listed patient charges for covered services at time of service",
        "Dental office can be changed for any reason; generally effective first day of next month",
        "Second opinion from a different network general dentist can be arranged through customer service",
      ],
      claimsAndWaiting: "No claim forms and no waiting periods for coverage.",
      preExistingConditions:
        "Pre-existing conditions are not excluded if procedures are covered by PCS; work already in progress exclusions may apply.",
    },
    enhancedPrograms: {
      oralHealthIntegrationProgram: {
        description:
          "May reimburse 100% of eligible out-of-pocket costs for certain dental procedures for qualifying members.",
        qualifyingConditions: [
          "Diabetes",
          "Heart disease",
          "Stroke",
          "Maternity",
          "Head and neck cancer radiation",
          "Organ transplants",
          "Chronic kidney disease",
        ],
      },
      includedSupportPrograms: [
        "Dental Information Line with trained professionals 24/7/365",
        "Cigna Identity Theft Program support (service program, not insurance)",
      ],
    },
    gvsVisionHighlights: {
      overview:
        "General Vision Services (GVS) provides vision benefits with national network access, online scheduling, mobile app support, and customer care.",
      keyPoints: [
        "Comprehensive vision examinations with licensed optometrists",
        "Wide frame and contact lens options through partner brands",
        "Plastic lenses, oversized, children polycarbonate, and GVS progressive lenses",
        "UV and scratch-resistant coatings as covered options under plans",
        "Unlimited adjustments and minor repairs for eyeglasses",
        "Manufacturing defect warranty on lenses, frames, and hinges up to one year",
        "Member portal access to benefits and provider search",
        "LASIK program access at nationwide locations with credentialed surgeons",
        "Hearing program through General Hearing Services (GHS)",
      ],
    },
    complianceNotes: [
      "Plan designs, covered services, and exclusions may vary by state and PCS.",
      "Some state-specific access and reimbursement rules apply (for example, Minnesota and Oklahoma).",
      "Cigna DHMO is not available in certain states and territories per official plan documentation.",
      "For complete coverage terms, use enrollment materials and official policy forms.",
    ],
    stateAvailability: {
      available: [
        "AL",
        "AR",
        "AZ",
        "CA",
        "CO",
        "CT",
        "DC",
        "DE",
        "FL",
        "GA",
        "IA",
        "ID",
        "IL",
        "IN",
        "KS",
        "KY",
        "LA",
        "MA",
        "MD",
        "MI",
        "MN",
        "MO",
        "MS",
        "NC",
        "NE",
        "NJ",
        "NV",
        "NY",
        "OH",
        "OK",
        "OR",
        "PA",
        "SC",
        "TN",
        "TX",
        "UT",
        "VA",
        "WI",
      ],
      notAvailable: [
        "AK",
        "HI",
        "ME",
        "MT",
        "NH",
        "ND",
        "RI",
        "SD",
        "VT",
        "WA",
        "WV",
        "WY",
        "NM",
      ],
    },
  },
} as const;
